Models/DocumentType.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Library_System.Models
{

    [Table("documen_types")]
    public class DocumentType
    {
        [Key]
        public int Id { get; set; }

        [Column("name")]
        [MaxLength(50, ErrorMessage = "Name cannot be longer than 50 characters")]
        public required string Name { get; set; }

        [Column("abbreviation")]
        [MinLength(1, ErrorMessage = "Abbreviation cannot be empty")]
        [MaxLength(10, ErrorMessage = "Abbreviation cannot be longer than 10 characters")]
        public required string Abbreviation { get; set; }

        [Column("description")]
        [MaxLength(100, ErrorMessage = "Description cannot be longer than 100 characters")]
        [RegularExpression(@"^[a-zA-Z0-9\s]+$", ErrorMessage = "Description can only contain letters, numbers, and spaces")]
        public string? Description { get; set; }

    }

}

Models/ErrorViewModel.cs
namespace Library_System.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Controllers/DocumentTypesController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Library_System.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Library_System.Controllers
{
    [Route("[controller]")]
    public class DocumentTypesController : Controller
    {
        private readonly ILogger<DocumentTypesController> _logger;

        private readonly AplicationDbContext _context;

        public DocumentTypesController(ILogger<DocumentTypesController> logger, AplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        

        public IActionResult Index()
        {   
            var AlldocumentTypes = _context.DocumentTypes.ToList();
            _logger.LogInformation("Index");
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        [Route("Error")]
        public IActionResult Error()
        {   
            return View("Error!");
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Library_System.Models;

namespace Library_System.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/DocumentTypes/Create.cshtml
<div class="text-center">

    <h1 class="display-4">Create Document Type</h1>

</div>

Views/DocumentTypes/Delete.cshtml
<div class="text-center">
    <h1 class="display-4">Delete Document Type</h1>
</div>

Views/DocumentTypes/Details.cshtml
<div class="text-center">

    <h1 class="display-4"><Details></Details> Document Type</h1>

</div>

Views/DocumentTypes/Edit.cshtml
<div class="text-center">

    <h1 class="display-4">Edit Document Type</h1>

</div>

Views/DocumentTypes/Index.cshtml
<div class="container">

    <h1>Document Types</h1>

    <p>
        <a asp-controller="DocumentTypes" asp-action="Create" class="btn btn-primary btn-lg" role="button">Create Document Type"></a>
        
    </p>

    <table class="table">
        <thead>
            <tr>
                <th>
                    Id
                </th>
                <th>
                    Name
                </th>
                <th>
                    Abbreviation
                </th>
                <th>
                    Description
                </th>
                <th>
                    Options
                </th>
            </tr>
    

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Library_System</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Library_System.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Library System</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DocumentTypes" asp-action="Index">Hola</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Library_System - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>